[build]
  publish = ".output/public"
  command = "npm run generate"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/education"
  to = "/work?tab=education"
  status = 301

[[redirects]]
  from = "/experience"
  to = "/work?tab=experience"
  status = 301

[[redirects]]
  from = "/research"
  to = "/work?tab=research"
  status = 301
