// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/1/2026, 11:37:23 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/plugins/**/*.{js,ts,mjs}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/composables/**/*.{js,ts,mjs}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/utils/**/*.{js,ts,mjs}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["23"] = "/Users/prasanthsasikumar/Documents/GitHub/ritisharma.com/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;